---
version: "3.7"

services:
  s3:
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9000:9000

  postgres:
    environment:
      POSTGRES_PASSWORD: pgadmin
    ports:
      - 5432:5432

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 8080:80
